### ISSUE TITLE
Why is RcppCoronaImmunitty_0.1.0.tar.gz an archive?

### ISSUE THREAD

**Issue by wwaites** [NaomiWaterlow/coronavirus_immunity#2]
This seems to be the model itself, included as an archive not as source code files in the repository. Is this software from somewhere else that has its own git repository? If yes, suggest using submodules (https://www.git-scm.com/docs/gitsubmodules). If no, the source files should ideally be in this repository directly.

**Comment by NaomiWaterlow** [comment]
It was for easy loading on AWS. I have added the scripts that contain the models to a reference foler.
