### ISSUE TITLE
How do I compile and run this software?

### ISSUE THREAD

**Issue by wwaites** [NaomiWaterlow/coronavirus_immunity#3]
Explicit instructions for compiling and running missing from the README.

How to compile the model?

Guessing that running the software means running `master_script.R`. Is this simply done as `R < master_script.R` or is something else required? If fitting and analysis are done separately, how does one do that?

(This is alluded to in the README but it would be better to have explicit instructions)

**Comment by NaomiWaterlow** [comment]
Clarified in the README
