### ISSUE TITLE
Metadata and provenance

### ISSUE THREAD

**Issue by wwaites** [NaomiWaterlow/coronavirus_immunity#4]
There are various CSV data files in the repository in `fitting_seasonal/fit` and `simulating_covid`. There are some `Rdata` files in `fitting_seasonal/analysis`. Are these input or output? If they are input, where do they come from and which scripts use them? If they are output, which scripts produce them? In both cases, what data is contained in them?

**Comment by NaomiWaterlow** [comment]
This has been clarified in the readme.
